#!/bin/bash

# Get a list of all Kotlin files that have been changed
changed_files=$(git diff --cached --name-only --diff-filter=d | grep "\.kt$")

# Run ktlint -F on each changed file
for file in $changed_files; do
  ktlint -F "$file"
  git add "$file"
done

# Exit successfully if no issues were found
exit 0
